services:
  db_server:
    image: ${DB:-mariadb:10.11}
    # mysql:mysql in MariaDB for Docker (https://stackoverflow.com/a/55241769/5155484)
    user: 999:999
    environment:
      MARIADB_ROOT_PASSWORD: "${TESTSUITE_PASSWORD:-my-secret-pw}"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-uroot", "-p${TESTSUITE_PASSWORD:-my-secret-pw}"]
      start_period: 10s
      interval: 5s
      timeout: 60s
      retries: 10
    networks:
      testing:
        aliases:
         - phpmyadmin_testing_db
    volumes:
      - mariadb-data:/var/lib/mysql

  phpmyadmin:
    build:
      context: ../../apache
    # www-data:www-data in Debian (https://stackoverflow.com/a/69290889/5155484)
    user: 33:33
    environment:
      PMA_HOST: db_server
      UPLOAD_LIMIT: 123M
      MAX_EXECUTION_TIME: 125
    volumes:
      - ../config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
    healthcheck:
      test: ["CMD", "curl", "-Ss", "http://localhost/robots.txt"]
      start_period: 5s
      interval: 3s
      timeout: 60s
      retries: 10
    networks:
      testing:
        aliases:
         - phpmyadmin_testing_apache
    depends_on:
      db_server:
        condition: service_healthy

  sut:
    # nobody:nobody
    user: 65534:65534
    depends_on:
      phpmyadmin:
        condition: service_healthy
      db_server:
        condition: service_healthy
    build:
      context: ../
    command: "/tests/testing/test-docker.sh"
    networks:
      testing:
    environment:
      TESTSUITE_HOSTNAME: phpmyadmin_testing_apache
      TESTSUITE_PORT: 80
      TESTSUITE_PASSWORD: "${TESTSUITE_PASSWORD:-my-secret-pw}"
      PMA_HOST: phpmyadmin_testing_db
      PMA_PORT: 3306
      SKIP_EXPOSE_PHP_TEST: true
    volumes:
      - ../../:/tests:ro
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /tests

networks:
    testing:
        driver: bridge

volumes:
  mariadb-data:
